name: Build Sentinel

on:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.2'
          cache: 'poetry'
      - run: poetry install

      - name: Start the api
        run: |
          poetry run uvicorn sentinel.api:app --host 0.0.0.0 --port 8000 --reload &

      - name: Unit testing
        run: |
          poetry run coverage run -m pytest tests/test_unit.py
          poetry run coverage report --fail-under 90

      - name: Regression testing
        run: |
          BASE_URL=http://localhost:8000 poetry run pytest tests/test_regression.py

      - name: Integration testing
        run: |
          poetry run pytest tests/test_integration.py